# backend/nixpacks.toml
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
aptPkgs = ["gcc", "g++", "libpq-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --no-input && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"