# Generated by Django 5.2.5 on 2025-08-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='disciplina',
            field=models.CharField(choices=[('boxeo', 'Boxeo'), ('muay-thai', 'Muay Thai'), ('k1', 'K-1 Kickboxing'), ('jiu-jitsu', 'Jiu-Jitsu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
