# Generated by Django 5.2.5 on 2025-08-09 22:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='contacto',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='disciplina',
            field=models.CharField(choices=[('boxeo', 'Boxeo'), ('muay-thai', 'Muay Thai'), ('k1', 'K-1'), ('jiu-jitsu', 'Jiu-Jitsu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 8 y 15 dígitos', regex='^\\d{8,15}$')]),
        ),
    ]
