# Generated by Django 5.2.5 on 2026-02-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
